language: python
sudo: false

python:
- 3.5
- 3.6
- 3.7-dev

install:
- pip install -U pip setuptools
- pip install pytest-runner

script:
- python setup.py test

before_deploy:
- echo "__version__ = '$(git describe --tags)'" > aioworkers_tg/version.py
